services:
  dnd-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dnd-master-app
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production